# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8mb4
  host: <%= ENV['HOSPITAL_DATABASE_PROD_HOST'] %>
  database: <%= ENV['HOSPITAL_DATABASE_PROD_HOST'] %>
  username: <%= ENV['HOSPITAL_DATABASE_PROD_USERNAME'] %>
  password: <%= ENV['HOSPITAL_DATABASE_PROD_PASSWORD'] %>

development:
  <<: *default
  adapter: mysql2
  encoding: utf8mb4
  host: <%= ENV['HOSPITAL_DATABASE_URL'] %>
  database: <%= ENV['HOSPITAL_DATABASE'] %>
  username: <%= ENV['HOSPITAL_DATABASE_USERNAME'] %>
  password:

test:
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['HOSPITAL_DATABASE_URL'] %>
  database: HOSPITAL_test<%= ENV['TEST_ENV_NUMBER'] %>
  username: <%= ENV['HOSPITAL_DATABASE_USERNAME'] %>
  password:
